### ISSUE TITLE
[Bug] Folder Name doesn't match title in TOC so addon doesn't show

### ISSUE THREAD

**Issue by nrodriguez** [MilleXIV/XIV_Databar#10]
From both Curse and WoWInterface the addon folder name is "XIV_Databar-1.1.0" which doesn't match the title set in the TOC, therefore it doesn't show up in the addons list or through the curse client.

```lua
## Interface: 70300
## Title: XIV_Databar
## Author: |cffbbbbbbMille|cff990000XIV|r
## Version: 1.0
## Notes: Adds a bottombar by the request of |cffffffffu/sammojo|r on Reddit, Icons made by |cffffffffu/sammojo|r. Previously maintained by |cff00FF99Saxitoxin|r.
## SavedVariables: TEST_CONFIG
## X-Issues: https://github.com/MilleXIV/XIV_Databar/issues
```

![image](https://cloud.githubusercontent.com/assets/798686/17459037/7bfaa5d0-5bf7-11e6-86a9-90c5957ad9db.png)

**Comment by MilleXIV** [comment]
I've got a minor update I want to put into master, as well as @Mikeprod's pull request. I'll reupload with those tonight and a better filename.

**Comment by MilleXIV** [comment]
Versions on Curse and WoWInterface should now have properly matching TOC and folder names.
