### ISSUE TITLE
Clicking "Mining" should open the Mining Skills panel

### ISSUE THREAD

**Issue by GoldFishie** [MilleXIV/XIV_Databar#14]
It'd make it consistent with clicking Engineering, Blacksmithing, or other professions bringing up their production windows.

**Comment by Mikeprod** [comment]
Thank you for your feedback. I have looked into it couple days ago before making my last pull request. But you made me have an idea on how to make it work regardless the client language

**Comment by MilleXIV** [comment]
Fixed in rewrite.
