### ISSUE TITLE
Gold Format Display Change

### ISSUE THREAD

**Issue by MilleXIV** [MilleXIV/XIV_Databar#15]
From [a comment on Curse](https://mods.curse.com/addons/wow/xiv-databar#c13):

> Hi what would I need to change to gold display format. Currently it is 999999g I would like to show it as 999.999g, essentially a dot after ever 1.000.

Would be best if an option. Easily localized with [BreakUpLargeNumbers](http://wow.gamepedia.com/API_BreakUpLargeNumbers).

**Comment by Mikeprod** [comment]
On top of that it could be great to reduce the size of the amount of gold, such as for 100.000 g converted into 100k g

**Comment by MilleXIV** [comment]
Fixed in rewrite to be localized, formatted, and with the option to shorten 100,000 to 100k.
