### ISSUE TITLE
[Bug] Guild online number not updating

### ISSUE THREAD

**Issue by Mikeprod** [MilleXIV/XIV_Databar#18]
I have noticed it and a comment on [curse](https://mods.curse.com/addons/wow/xiv-databar?comment=23) underlined it too. Most of the time the online guildies number does not update unless it gets refreshed by opening the guild Ui. 

The first glance at the code tells me it's a weird thing happening.

**Comment by MilleXIV** [comment]
Hmm...this is probably due to not calling GuildRoster() frequently enough. Should be called with the OnEnter and OnEvent scripts before doing anything else. Will add to rewrite's log.

**Comment by Mikeprod** [comment]
I'd rather think specifying the event to be GUILD_ROSTER_UPDATE to update the number of online guild members. No time to try / develop the fix.

**Comment by MilleXIV** [comment]
It currently already registers for GUILD_ROSTER_UPDATE, which is very oddly triggered. A call to GuildRoster (which the Guild UI does) forces the event to fire. Just need to make sure I run it in a way that doesn't cause a loop.

**Comment by Mikeprod** [comment]
If you want to check a module I made for auto inviting guildies that works perfectly. It may inspire some things [FS_Core Autoinvite](https://github.com/Mikeprod/FS_Core/blob/master/AutoInvite.lua)

**Comment by MilleXIV** [comment]
This should be working now. If anybody still has any problems go ahead and post here, but I'll close this in say...10 days if no update.
