### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Therevrun** [MilleXIV/XIV_Databar#21]
Message: Interface\AddOns\XIV_Databar\modules\currency.lua:56: attempt to index global 'db' (a nil value)
Time: 08/29/16 19:48:42
Count: 1
Stack: ...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:317: in function <...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:300>
(tail call): ?
Interface\AddOns\XIV_Databar\modules\currency.lua:56: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

Everything is updated then this started to throw this error.

**Comment by MilleXIV** [comment]
Bug is fixed in latest commit.
