### ISSUE TITLE
Spec icon isnt working when the bar is at the top

### ISSUE THREAD

**Issue by dl123456** [MilleXIV/XIV_Databar#22]
With having the databar at the top, spec icon does nothing when I click on it, as it supposed to let me choose when spec to swtich to/loot spec. It works fine when it is on the bottom.

Tested Class: DH, DK

**Comment by MilleXIV** [comment]
Should be (mostly) fixed. Only issue is that the popup maintains a weird positioning if switched without a UI reload. Will keep this open to look into that.

**Comment by MilleXIV** [comment]
Oh hey, just realized this is the same issue as #42. Should be fixed in that commit.
