### ISSUE TITLE
Fork Into New Addon

### ISSUE THREAD

**Issue by nrodriguez** [MilleXIV/XIV_Databar#3]
I love that you fixed it but you should probably fork this into a new addon on curse or wowinterface.

**Comment by Mikeprod** [comment]
Good idea if the 1st author does not do any update in the couple next weeks

**Comment by MilleXIV** [comment]
That is the intent. I have a comment up on the original WoW Interface page asking about taking it over. If I don't hear anything by August 1 I'm going to rename it and push to WoW Interface and Curse.

**Comment by MilleXIV** [comment]
Name updated, and pushed to [WoW Interface](http://www.wowinterface.com/downloads/info24105-XIV_Databar.html) and Curse (still waiting for their repo to generate the files).

**Comment by MilleXIV** [comment]
Got tired of waiting and uploaded a zip to Curse: https://mods.curse.com/addons/wow/xiv-databar
