### ISSUE TITLE
addon preventing interaction with artifact forge

### ISSUE THREAD

**Issue by Ramzie** [MilleXIV/XIV_Databar#30]
The addon when used in conjunction with Exorsus Raid Tools prevents interaction with the artifact forge until a /reloadui is performed.

**Comment by MilleXIV** [comment]
That...is incredibly strange. I'll have to install that and poke around with it later.

**Comment by Amanthuul** [comment]
Same happens with AdiButtonAuras and WeakAuras 2. 
All 3 have libartifactdata in libs folder.

Happens when changing zone (krasus' landing - dalaran, dalaran - class hall, etc.)

RealUI author encountered this too (and probably fixed), maybe he can help.
http://www.wowinterface.com/forums/showthread.php?t=54341

**Comment by MilleXIV** [comment]
Now that is super useful @Amanthuul. I'll have to see what Gethe did in RealUI to deal with that, and if not move to just using the built in Blizzard functions.

**Comment by MilleXIV** [comment]
I pulled in what Gethe changed for RealUI and that seems to have fixed the issue.

**Comment by Amanthuul** [comment]
Got
`Message: Interface\FrameXML\MainMenuBar.lua:126: Usage: GetCostForPointAtRank(rank)
Time: 09/02/16 17:58:32
Count: 1
Stack: [C]: in function `GetCostForPointAtRank'
Interface\FrameXML\MainMenuBar.lua:126: in function <Interface\FrameXML\MainMenuBar.lua:124>
...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:230: in function <...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:225>
...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:291: in function <...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:278>
...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:309: in function <...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:308>

Locals: (*temporary) = nil`
on first load after update and if to delete config file from savedvariables - on first load too.
Coflicts with ExRT again.
Zone chaiging doesn't trigger it anymore.

**Comment by MilleXIV** [comment]
Yeah, I'm reopening this. It seems that LibArtifactData has quite a few issues, and the dev is away from WoW until Sunday. x.x

**Comment by Amanthuul** [comment]
If to disable Talents module, then enable, with ExRT i get
`Message: Interface\FrameXML\MainMenuBar.lua:126: Usage: GetCostForPointAtRank(rank)
Time: 09/02/16 18:14:00
Count: 1
Stack: [C]: in function `GetCostForPointAtRank'
Interface\FrameXML\MainMenuBar.lua:126: in function <Interface\FrameXML\MainMenuBar.lua:124>
...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:230: in function <...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:225>
...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:291: in function <...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:278>
...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:493: in function `ForceUpdate'
Interface\AddOns\XIV_Databar\modules\talent.lua:42: in function <Interface\AddOns\XIV_Databar\modules\talent.lua:30>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function <...ddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua:551>
(tail call): ?
...
[C]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:799: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:614>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...ce\AddOns\XIV_Databar\Libs\AceGUI-3.0\AceGUI-3.0.lua:314: in function `Fire'
...ar\Libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:68: in function <...ar\Libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57>

Locals: <none>`

If then try to get tooltip, it says
`Message: Interface\AddOns\XIV_Databar\modules\talent.lua:458: attempt to compare number with nil
Time: 09/02/16 18:17:54
Count: 2
Stack: Interface\AddOns\XIV_Databar\modules\talent.lua:458: in function `ShowTooltip'
Interface\AddOns\XIV_Databar\modules\talent.lua:193: in function <Interface\AddOns\XIV_Databar\modules\talent.lua:188>

Locals: self = <table> {
 lootSpecOptionString = <unnamed> {
 }
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua:398
 RegisterFrameEvents = <function> defined @Interface\AddOns\XIV_Databar\modules\talent.lua:173
 OnInitialize = <function> defined @Interface\AddOns\XIV_Databar\modules\talent.lua:12
 Enable = <function> defined @Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua:325
 UnregisterAllEvents = <function> defined @Interface\AddOns\ExRT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:202
 CreateFrames = <function> defined @Interface\AddOns\XIV_Databar\modules\talent.lua:158
 EnableModule = <function> defined @Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua:241
 IterateEmbeds = <function> defined @Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua:473
 ShowTooltip = <function> defined @Interface\AddOns\XIV_Databar\modules\talent.lua:441
 specFrame = <unnamed> {
 }
 defaultModuleLibraries = <table> {
 }
 talentFrame = <unnamed> {
 }
 lootSpecPopupTexture = <unnamed> {
 }
 specOptionString = <unnamed> {
 }
 currentSpecID = 1
 specPopupTexture = <unnamed> {
 }
 specPopup = <unnamed> {
 }
 baseName = "XIV_Databar"
 specBar = <unnamed> {
 }
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua:440
 specText = <unnamed> {
 }
 specIcon = <unnamed> {
 }
 curArtifactId = 128935
 name = "XIV_Databar_TalentModule"
 LAD = <table> {
 }
 IsEnabled = <function> defined @Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua:482
 orderedModules = <table> {
 }
 classIcon = "Interface\AddOns\XIV_Databar\media\spec\SHAMAN"
 DisableModule = <function> defined @Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua:381
 defaultModuleState = true
 lootSpecButtons = <table> {
 }
 optionTextExtra = 4
 extraPadding = 9
 RegisterMessage = <function> defined @Interface\AddOns\ExRT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 UnregisterMessage = <function> defined @Interface\AddOns\ExRT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:181
 CreateSpecPopup = <function> defined @Interface\AddOns\XIV_Databar\modules\talent.lua:249
 specCoords = <table> {
 }
 currentLootSpecID = 262
 specBarBg = <unnamed> {
 }
 Refresh = <function> defined @Interface\AddOns\XIV_Databar\modules\talent.lua:53
 IsModule = <function> defined @Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua:248
 GetDefaultOptions = <function> defined @Interface\AddOns\XIV_Databar\modules\talent.lua:475
 SetDefaultModuleState = <function> defined @Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua:418
 CreateLootSpecPopup = <function> defined @Interface\AddOns\XIV_Databar\modules\talent.lua:339
 UpdateArtifactBar = <function> defined @Interface\AddOns\XIV_Databar\modules\talent.lua:152
 SetEnabledState = <function> defined @Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 GetConfig = <function> defined @Interface\AddOns\XIV_Databar\modules\talent.lua:484
 enabledState = true
 OnDisable = <function> defined @Interface\AddOns\XIV_Databar\modules\talent.lua:46
 RegisterEvent = <function> defined @Interface\AddOns\ExRT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 UnregisterAllMessages = <function> defined @Interface\AddOns\ExRT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:202
 OnEnable = <function> defined @Interface\AddOns\XIV_Databar\modules\talent.lua:30
 lootSpecPopup = <unnamed> {
 }
 Ne`

**Comment by MilleXIV** [comment]
Yeah, seems LibArtifactData is broke as heck. If you want to stop the errors, I just did an edit within Github to modules/talent.lua. Pulling that should stop the errors.

**Comment by Rainrider** [comment]
@MilleXIV I'm only able to reproduce the issues posted when using Exorsus Raid Tools. Btw go have a look at their code.

Also I don't get it what good it is if everybody runs their own forks here and why just not issue a PR instead, which I would have accepted. But well ...

**Comment by MilleXIV** [comment]
With v2.0.4 I've pushed some updates from the LibArtifactData repo and re-enabled artifact stuff.

**Comment by Mikeprod** [comment]
@Ramzie Is this issue solved ? If so, please close this issue. Thank you.
