### ISSUE TITLE
Level and profession progress bars updates only when changing Bar padding

### ISSUE THREAD

**Issue by Amanthuul** [MilleXIV/XIV_Databar#36]
Subj.
![wowscrnshot_090216_101826](https://cloud.githubusercontent.com/assets/18071324/18195954/4b825ac8-70f7-11e6-8e96-2eb85264c783.jpg)
![wowscrnshot_090216_101833](https://cloud.githubusercontent.com/assets/18071324/18195959/52cec712-70f7-11e6-83be-4d911916c7cc.jpg)
![wowscrnshot_090216_101837](https://cloud.githubusercontent.com/assets/18071324/18195963/5898bdec-70f7-11e6-9535-ca53a605b19e.jpg)
![wowscrnshot_090216_101839](https://cloud.githubusercontent.com/assets/18071324/18195966/5c96496e-70f7-11e6-98e1-592ad1793f93.jpg)

**Comment by MilleXIV** [comment]
I've added a timed refresh to the core. That should clear up these issues. Let me know if you're still experiencing them after updating.

**Comment by Amanthuul** [comment]
Still the same.

**Comment by MilleXIV** [comment]
Alright, I'll look into this more later.

**Comment by Amanthuul** [comment]
Oh, it's only when padding = 0

**Comment by MilleXIV** [comment]
That actually helps quite a bit. I definitely know what's going on now. Need to change how I calculate sizes for things with bars. The short of it: I'm accidentally setting the bar's height to a negative number...which is causing these issues.

**Comment by MilleXIV** [comment]
So this should have been fixed in 879ba8f566a522a823e262680ce3b3ccb796055b. The bars now have a minimum height of 2.

**Comment by Mikeprod** [comment]
@Amanthuul if this issue is solved you can close this issue in order to clean up the issue section. Thanks

**Comment by Amanthuul** [comment]
Profession levels and character level don't disappear anymore. 
Artifact power bar still affected by this.

**Comment by Mikeprod** [comment]
I had noticed the problem before. It should be fixed now.
