### ISSUE TITLE
[Enhancement] Clickable Tradeskill

### ISSUE THREAD

**Issue by Kiseph** [MilleXIV/XIV_Databar#40]
Is it possible to have the profession windows open when clicking on the Tradeskill modules? For example, if I click on Leatherworking, it opens up the recipe list for Leatherworking.

**Comment by Mikeprod** [comment]
So far it does. If not you probably have an addon preventing it.

**Comment by Kiseph** [comment]
That's weird, I was able to click other modules just fine. I figured out the problem, thank you!
