### ISSUE TITLE
[Enhancement] Screen Adjust

### ISSUE THREAD

**Issue by Kiseph** [MilleXIV/XIV_Databar#41]
I've been using TitanPanel for a long time. Loved this addon and wanted to use this over TitanPanel. The only issue I'm having is that TitanPanel had an option where it would adjust any blizzard UI frames in the way of the bar. So for example, my buff/debuff bars and quest logs would move down. Would love an option for this.

Here's an example without TitanPanel on:

![NoScreenAdjust](http://i.imgur.com/nc2baLF.png)

And an example with TitanPanel enabled in the background

![NoScreenAdjust](http://i.imgur.com/KYI42di.png)

PS: Sorry for all the posts! And thank you as well!

**Comment by Mikeprod** [comment]
I'll look into it with my pull request ;)

**Comment by Kiseph** [comment]
You are amazing <3 Let me know if you need anything.

**Comment by Mikeprod** [comment]
I found a way to do it, however even TitanPanel tries hard to keep the offset in the class hall. It will be done with further investigation with Mille

**Comment by Mikeprod** [comment]
But (hideorderall)[https://mods.curse.com/addons/wow/hideorderhallbar] fixes it I'll add that after furher bug fixes

**Comment by Mikeprod** [comment]
Hey @Kiseph I fixed it for good ! You can checkout my repo and get the last version of the branch improvements

**Comment by Mikeprod** [comment]
@Kiseph I am currently browsing the solved issues. Could you please close this one ? Thanks

**Comment by NerfOnline** [comment]
My apologies, didn’t realize that this was still open. Closed.
