### ISSUE TITLE
Talents Module: Left clicking opens left-click to the bottom (bottom bar) (pic)

### ISSUE THREAD

**Issue by Kimab** [MilleXIV/XIV_Databar#47]
basically the talents module opens the various specs to the bottom, out of the screen, on a bottom attached bar. same for the loot selection.
![xiv databar talents bug](https://cloud.githubusercontent.com/assets/21992837/18234980/184a7fd6-7314-11e6-98ad-239071438555.jpg)

**Comment by MilleXIV** [comment]
I believe this is the same issue as #42, so should be fixed in Git. I'll be pushing out a build soonish with bug fixes.
