### ISSUE TITLE
[Bug] System module doesn't show

### ISSUE THREAD

**Issue by katur239** [MilleXIV/XIV_Databar#58]
If you disable the gold module the next time the UI is loaded then the system module will not appear aswell.

Like wise even if the travel module is also disabled. The travel module is all that actually shows.

**Comment by Mikeprod** [comment]
Fixed on my improvements branch [commit](https://github.com/Mikeprod/XIV_Databar/commit/1b7f71824cef55886b4edf8e7e4b15199efed447)

**Comment by Mikeprod** [comment]
@katur239 please close this issue for more readability of what is to be done concerning the addon.

**Comment by katur239** [comment]
Sorry! :3
