### ISSUE TITLE
Localisation help needed DE, RU, ZH

### ISSUE THREAD

**Issue by Mikeprod** [MilleXIV/XIV_Databar#64]
I developed new fetures that need translation on my repo. I therefore need help to translate them in :

- [ ] German
- [x] Russian
- [x] Chinese

Thank you

**Comment by Amanthuul** [comment]
I tried to pull request Russian translation, but can't without permissions.
Also, what "No tag" stand for?

**Comment by Mikeprod** [comment]
You tried to pull request on my repo and did not work ?

I don't know the context where you might get have the "No tag" thing, but it means that no tag in the repo have been set like `git tag - a v2.0.5`

**Comment by Amanthuul** [comment]
I'm about [No tag] in addon's translation file.

And i foud, what is main problem. It's impossible to fork a fork :(
So it opens as your fork and I can't make new branch to pull request to your "master" and i ofc can't push to your branch because lack of permissions.

**Comment by Mikeprod** [comment]
The [No tag] is for BNet friends if they have no battle tag. Apparently it might be possible :D 

You should therefore update your pull request here for the localization, I will merge the difference myself.

**Comment by Amanthuul** [comment]
Ok, here it is.
[ruRU.lua.txt](https://github.com/MilleXIV/XIV_Databar/files/591673/ruRU.lua.txt)

And friend interatctions on friends tooltip like "whisper" or "invite" have no translation strings. Can you add them?

**Comment by Mikeprod** [comment]
For the tooltips I replaced the strings with the Blizzard defaults.

Edit : Can you give me some feedback before pushing to Curse ?

**Comment by Amanthuul** [comment]
Ok. It's now translated. But looks a bit weird.

**Comment by Mikeprod** [comment]
How weird ? :p

**Comment by Amanthuul** [comment]
It's just "/w Battle.net" and "/w Character".
Doesn't look like description anymore, now it just chat command.
Invite looks great.

**Comment by Mikeprod** [comment]
Ok I'll let you translate the 2 additions then

**Comment by Amanthuul** [comment]
[ruRU.lua.txt](https://github.com/MilleXIV/XIV_Databar/files/592676/ruRU.lua.txt)

**Comment by Mikeprod** [comment]
Thanks. Updated on Curse too ;)

**Comment by Mikeprod** [comment]
@Amanthuul I had a pull request for the Chinese locale in my fork this morning. I suppose the problem is that you cannot pull request on a fork when you have a pull request opened on the original repo ...

@yaoenqi pointed out that I had not translated the Master Volume, I require therefore one line of translation :D

**Comment by Mikeprod** [comment]
Well I added some features this morning. @Amanthuul @PhatsoTheGhostlyTauren @yaoenqi Your help is needed ;) I will push the update to curse when mostly/all translated.

**Comment by Amanthuul** [comment]
[ruRU.lua.txt](https://github.com/MilleXIV/XIV_Databar/files/594596/ruRU.lua.txt)

**Comment by PhatsoTheGhostlyTauren** [comment]
IIRC you have to have your pull request accepted by @MilleXIV first. then i can pull from Mille's Master to add the missing Translation from my branch

**Comment by Mikeprod** [comment]
@PhatsoTheGhostlyTauren better pull directly from my [fork](https://github.com/Mikeprod/XIV_Databar/), then pull request there or do like @Amanthuul and enclose the translated file here.

**Comment by Mikeprod** [comment]
@PhatsoTheGhostlyTauren you can now translate the needed strings [here](https://wow.curseforge.com/projects/xiv_databar/localization/) They are defaulted to the English ones.
