### ISSUE TITLE
2.0.10 enable custom font, have gold module enabled with show free bag space unchecked, and reload throws error

### ISSUE THREAD

**Issue by ceylina** [MilleXIV/XIV_Databar#65]
Message: Interface\AddOns\xiv_databar\modules\gold.lua:82: <unnamed>:SetText(): Font not set
Time: 11/12/16 10:45:04
Count: 1
Stack: [C]: in function `SetText'
Interface\AddOns\xiv_databar\modules\gold.lua:82: in function `Refresh'
Interface\AddOns\xiv_databar\modules\gold.lua:31: in function <Interface\AddOns\xiv_databar\modules\gold.lua:19>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ce\AddOns\Dominos\libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function <...ce\AddOns\Dominos\libs\AceAddon-3.0\AceAddon-3.0.lua:551>
(tail call): ?
Interface\AddOns\xiv_databar\modules\gold.lua:242: in function <Interface\AddOns\xiv_databar\modules\gold.lua:239>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:799: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:614>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...ce\AddOns\xiv_databar\Libs\AceGUI-3.0\AceGUI-3.0.lua:314: in function `Fire'
...ar\Libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:68: in function <...ar\Libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57>

Locals: <none>

**Comment by ceylina** [comment]
You can resolve this by calling setfont in the else statement (need to declare that before settext anyway)

So above line 82 add this and it should resolved the issue

self.bagText:SetFont(xb:GetFont(db.text.fontSize))

**Comment by Mikeprod** [comment]
Indeed this is an inconvenient error ;) It will be fixed in the future patch. You can close this issue. Thank you.
