### ISSUE TITLE
7.2 patch breaks artifact traits 

### ISSUE THREAD

**Issue by Demonstorm** [MilleXIV/XIV_Databar#68]
been using this for a few weeks and was working great till patch 7.2 now i cant access my artifact traits if it is loaded ..thanks in advance

**Comment by Mikeprod** [comment]
This addon is now deprecated, thanks to refer [here](https://github.com/Mikeprod/XIV_Databar) where 2 issues are opened. Therefore please close this issue.

**Comment by Demonstorm** [comment]
okay I will close it but update did not fix problem something in your add on is stopping artifact traits from opening


________________________________

**Comment by Demonstorm** [comment]
okay closed like you asked but like still cant see artifact traits.....love the addon BTW

**Comment by Mikeprod** [comment]
A new version is pending fixing this issue.

**Comment by Demonstorm** [comment]
thank you so much ...I am still using it at the moment and just disabling it when I need to keep the awesome work

________________________________
