### ISSUE TITLE
Font scaling with UI

### ISSUE THREAD

**Issue by Mikeprod** [MilleXIV/XIV_Databar#8]
Bug reported on Curse with this [comment](https://mods.curse.com/addons/wow/xiv-databar?comment=1)

**Comment by MilleXIV** [comment]
With the rewrite the bar will scale based on font size instead of having to set them individually. Might split padding option from just 1 option to options for sides and an option for top/bottom, but not sure if needed.

**Comment by MilleXIV** [comment]
Rewrite scales the bar height off font size and bar padding setting.
